name: Deploy Immutable AMI
on:
  #workflow_dispatch: 
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Build Java App
      - name: Set Up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build with Maven
        run: mvn -B -DskipTests package
      
      # trivy scan build
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'target/'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-fs-report.json'
          #exit-code: '1'  # This fails the build if a CRITICAL issue is found
          severity: 'CRITICAL'

        

      - name: Rename JAR (for consistency with Ansible)
        run: mv target/EduSched-0.0.1-SNAPSHOT.jar target/app.jar
  
      - name: Verify JAR location
        run: ls -l target/app.jar
      
      # 3. Setup AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 4. Initialize Packer
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Packer Init
        run: packer init ./Packer/build.pkr.hcl

      # 5. Build AMI
      - name: Build AMI
        id: build-image
        run: |
          packer build ./Packer/build.pkr.hcl
          
          # Use jq to grab the ID from the file Packer just created
          
          AMI_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d: -f2)
          
          echo "AMI_ID=$AMI_ID" >> $GITHUB_OUTPUT
          echo "Created AMI: $AMI_ID"
      
      # trivy ami scan
      - name: Trivy AMI Scan (OS + Full Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ami:${{ steps.build-image.outputs.ami_id }}'
          scan-type: 'image'
          severity: 'CRITICAL'
          format: 'table'
          output: 'trivy-ami-report.json'
         # exit-code: '1'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1


      # 6. Update ASG (The Zero Downtime Deployment)
      - name: Refresh ASG
        env:
            ASG_NAME: "schedemy01-ASG"
            NEW_AMI: ${{ steps.build-image.outputs.ami_id }}
            LT_NAME: "schedemy01-template"
        run: |
          echo "Updating ASG $ASG_NAME with new AMI: $NEW_AMI"
          
          # Check if the ID is empty before proceeding
          if [ -z "$NEW_AMI" ]; then
            echo "Error: AMI_ID is empty."
            exit 1
          fi
         
          # 1. Create a new Launch Template Version with the new AMI
    
          aws ec2 create-launch-template-version \
            --launch-template-name $LT_NAME \
            --source-version "\$Latest" \
            --launch-template-data "{\"ImageId\":\"$NEW_AMI\"}"

          # 2. Tell ASG to start an Instance Refresh
          # This slowly replaces instances. MinHealthyPercentage=50 means at least half stay up.
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name $ASG_NAME \
            --preferences '{"MinHealthyPercentage": 50, "InstanceWarmup": 60}'
     
      # reports
      - name: Upload Scan Artifact
        uses: actions/upload-artifact@v4
        if: always() # Ensures reports are uploaded even if a scan fails
        with:
          name: security-audit-reports
          path: |
            trivy-fs-report.json
            trivy-ami-report.json
          retention-days: 30
    
      
